src/AppBundle/Entity/Article.php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\ReviewQuestion;
use AppBundle\Entity\Traits\ActivityLoggableTrait;
use AppBundle\Entity\Traits\TimestampableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * Article entity.
 */
class Article
{

    const STATUS_PUBLISHED = 'P';
    const STATUS_DRAFT = 'D';

    use TimestampableTrait;
    //use ActivityLoggableTrait;
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @var \Doctrine\Common\Collections\Collection
     * @Assert\Count(min=1, minMessage="There must be at least one author")
     * @Assert\Valid()
     */
    private $authors;

    /**
     * @var \Doctrine\Common\Collections\Collection
     * @Assert\Valid()
     */
    private $keywords;
    /**
     * @Assert\NotBlank()
     * @Assert\Length(min=2, max=20)
     */
    private $article_type;
    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\Length(min=4, max=6)
     */
    private $publish_date;
    /**
     * @var string
     */
    private $doi='';
    /**
     * @var string
     * @Assert\Url()
     */
    private $url='';
    /**
     * @var \AppBundle\Entity\Publisher
     * @Assert\Valid()
     */
    private $publisher;
    /**
     * @var \AppBundle\Entity\Journal
     * @Assert\Valid()
     */
    private $journal;
    /**
     * @var string
     */
    private $bibtex;
    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     */
    private $references;

    /**
     * @var ArticleReview
     */
    private $review;

    private $owner;

    private $status;

    private $comment_count=0;

    public function __construct()
    {
        $this->authors = new ArrayCollection();
        $this->keywords = new ArrayCollection();
        $this->references = new ArrayCollection();
    }

    /**
     * Get id
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set title
     * @param string $title
     * @return Article
     */
    public function setTitle($title) {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     * @return string
     */
    public function getTitle() {
        return $this->title;
    }

    public function addAuthor(ArticleAuthor $author) {
        $this->authors[] = $author;
    }

    public function removeAuthor(ArticleAuthor $author) {
        $this->authors->removeElement($author);
    }

    public function getAuthors() {
        return $this->authors;
    }

    /**
     * @return string
     */
    public function getArticleType() {
        return $this->article_type;
    }

    /**
     * @param mixed $article_type
     * @return Article
     */
    public function setArticleType($article_type) {
        $this->article_type = $article_type;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPublishDate() {
        return $this->publish_date;
    }

    /**
     * @param mixed $publish_date
     * @return Article
     */
    public function setPublishDate($publish_date) {
        $this->publish_date = $publish_date;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getDoi() {
        return $this->doi;
    }

    /**
     * @param mixed $doi
     * @return Article
     */
    public function setDoi($doi) {
        $this->doi = $doi;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getUrl() {
        return $this->url;
    }

    /**
     * @param mixed $url
     * @return Article
     */
    public function setUrl($url) {
        $this->url = $url;
        return $this;
    }

    /**
     * @return Publisher
     */
    public function getPublisher() {
        return $this->publisher;
    }

    /**
     * @param Journal|null $publisher
     * @return Article
     */
    public function setPublisher($publisher) {
        $this->publisher = $publisher;
        return $this;
    }

    public function addKeyword(Keyword $keyword) {
        $this->keywords[] = $keyword;
    }

    public function removeKeyword(Keyword $keyword) {
        $this->keywords->removeElement($keyword);
    }

    public function getKeywords() {
        return $this->keywords;
    }
    /**
     * @return Journal
     */
    public function getJournal() {
        return $this->journal;
    }

    /**
     * @param Journal|null $journal
     */
    public function setJournal($journal) {
        $this->journal = $journal;
    }

    /**
     * @return mixed
     */
    public function getBibtex() {
        return $this->bibtex;
    }

    /**
     * @param string $bibtex
     * @return Article
     */
    public function setBibtex($bibtex) {
        $this->bibtex = $bibtex;
        return $this;
    }

    public function addReference(Reference $reference) {
        $reference->setArticle($this);
        $this->references[] = $reference;
    }

    public function removeReference(Reference $reference) {
        $this->references->removeElement($reference);
    }

    public function setReview($review) {
        $this->review = $review;
        return $this;
    }

    /**
     * @return ArticleReview
     */
    public function getReview() {
        return $this->review;
    }

    public function setOwner($owner) {
        $this->owner = $owner;
        return $this;
    }

    /**
     * @return User
     */
    public function getOwner() {
        return $this->owner;
    }

    public function getStatus() {
        return $this->status;
    }

    public function setStatus($status) {
        $this->status = $status;
        return $this;
    }

    public function __toString() {
        return $this->title;
    }

    public function canBePublished() {
        $out = false;
        if(is_object($this->getReview())) {
            $out = true;
        }
        return $out;
    }

    public function getCommentCount() {
        return $this->comment_count;
    }

    public function setCommentCount($count) {
        $this->comment_count = $count;
        return $this;
    }
}

src/AppBundle/Entity/ArticleComment.php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Traits\TimestampableTrait;

class ArticleComment {

    use TimestampableTrait;

    private $id;
    /**
     * @var Article
     */
    private $article;
    /**
     * @var User
     */
    private $commenter;
    /**
     * @var string
     */
    private $comment_text;

    public function getId() {
        return $this->id;
    }

    public function setId($id) {
        $this->id = $id;
        return $this;
    }

    public function getArticle() {
        return $this->article;
    }

    public function setArticle(Article $article) {
        $this->article = $article;
    }

    /**
     * @return User
     */
    public function getCommenter() {
        return $this->commenter;
    }

    /**
     * @param User $commenter
     * @return $this
     */
    public function setCommenter(User $commenter) {
        $this->commenter = $commenter;
        return $this;
    }

    public function getCommentText() {
        return $this->comment_text;
    }

    public function setCommentText($text) {
        $this->comment_text = $text;
        return $this;
    }

}

src/AppBundle/Entity/Author.php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Traits\TimestampableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

class Author {

    use TimestampableTrait;

    private $id;
    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\Length(min=2)
     */
    private $given;
    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\Length(min=2)
     */
    private $family;
    private $affiliation;
    private $article_count=0;
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $articles;

    public function __construct() {
        $this->articles = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId() {
        return $this->id;
    }

    /**
     * @param mixed $id
     * @return Author
     */
    public function setId($id) {
        $this->id = $id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getGiven() {
        return $this->given;
    }

    /**
     * @param mixed $given
     * @return Author
     */
    public function setGiven($given) {
        $this->given = $given;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getFamily() {
        return $this->family;
    }

    /**
     * @param mixed $family
     * @return Author
     */
    public function setFamily($family) {
        $this->family = $family;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getAffiliation() {
        return $this->affiliation;
    }

    /**
     * @param mixed $affiliation
     * @return ArticleAuthor
     */
    public function setAffiliation($affiliation) {
        $this->affiliation = $affiliation;
        return $this;
    }

    public function addArticle(Article $article) {
        $this->articles[] = $article;
    }

    public function getArticles() {
        return $this->articles;
    }

    public function removeArticle(Article $article) {
        $this->articles->removeElement($article);
    }

    public function getArticleCount() {
        return $this->article_count;
    }

    public function setArticleCount($count) {
        $this->article_count = $count;
        return $this;
    }
}

src/AppBundle/Resources/views/Article/_article_comments.html.twig
{% import '@App/Article/article_macros.html.twig' as amacros %}

<div class="blog-comments">
    <h3 class="sbold blog-comments-title">{{ "app.article.comments"|trans }}{% if comments|length %} ({{ comments|length }}){% endif %}</h3>
    {% if comments|length %}
    <div class="c-comment-list">
        {% for comment in comments %}
        {{ amacros.renderComment(comment) }}
        {% endfor %}
    </div>
    {% endif %}
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        {{ render(controller('AppBundle:ArticleComment:commentForm', {'articleId': article.id})) }}
    {% else %}
        <p>
            <a class="btn btn-success" href="{{ path('fos_user_security_login', {'redirect_to': app.request.pathInfo}) }}">
                <i class="fa fa-sign-in" aria-hidden="true"></i> {{ 'users.general.login'|trans }}
            </a>
            {{ 'app.article.login_to_publish_a_comment'|trans }}
        </p>
    {% endif %}

</div>

src/AppBundle/Resources/views/Article/_article_info.html.twig
{% import 'SlxMetronicBundle::metronic_macros.html.twig' as metronic %}
{% import '@App/Article/article_macros.html.twig' as amacros %}

<dl class="dl-horizontal single-article-info">
    <dt>{{ 'app.article.article_type'|trans }}</dt>
    <dd>{{ ('app.article.type_' ~ article.articleType)|trans }}</dd>
    <dt>{{ 'app.article.title'|trans }}</dt>
    <dd>{{ article.title }}</dd>
    <dt>{{ 'app.article.authors'|trans }}</dt>
    <dd>{{ amacros.renderArticleAuthors(article.authors) }}</dd>
    {%  if article.publishDate %}
        <dt>{{ 'app.article.year'|trans }}</dt>
        <dd>{{ article.publishDate }}</dd>
    {% endif %}
    {%  if article.doi %}
        <dt>{{ 'app.article.doi'|trans }}</dt>
        <dd>{{ article.doi }}</dd>
    {% endif %}
    {%  if article.url %}
        <dt>{{ 'app.article.url'|trans }}</dt>
        <dd>{{ article.url }}</dd>
    {% endif %}
    {%  if article.publisher %}
        <dt>{{ 'app.article.publisher'|trans }}</dt>
        <dd>{{ article.publisher.title }}</dd>
    {% endif %}
    {%  if article.journal %}
        <dt>{{ 'app.article.journal'|trans }}</dt>
        <dd>{{ article.journal.title }}</dd>
    {% endif %}
</dl>

src/AppBundle/Resources/views/Article/_article_review.html.twig
{% import 'SlxMetronicBundle::metronic_macros.html.twig' as metronic %}
{% import '@App/Article/article_macros.html.twig' as amacros %}

{% set review = article.review %}
{% if review %}
    <h4 class="sbold">{{ 'app.article.review'|trans }}</h4>
    <p>{{ review.reviewText|md2html }}</p>
    <dl class="dl-horizontal single-article-review">
        {% for q in review.questions %}
            {% if not q.getNotApply %}
                <dt>{{ q.question.question }}</dt>
                <dd>{{ renderQuestionAnswer(q) }}</dd>
            {% endif %}
        {% endfor %}
    </dl>

{% endif %}

src/AppBundle/Resources/views/Article/_editor_actions.html.twig
{% if block('portletTools') is defined %}
    {% set _block = block('portletTools') %}
{% else %}
    {% set _block = "" %}
{% endif %}
{% if _block is not empty %}
    <div class="blog-single-sidebar-recent">
        <h4 class="blog-sidebar-title uppercase"><i class="fa fa-gears"></i> Editor actions</h4>
        <ul>
            {{ block('portletTools') }}
        </ul>
    </div>
{% endif %}

src/AppBundle/Resources/views/Article/article_macros.html.twig
{% macro renderArticleTags(keywords, style) %}
    {% if keywords is not empty %}
        {% if style=='side' %}
        <div class="blog-single-sidebar-tags">
            <h3 class="blog-sidebar-title uppercase">article tags</h3>
            {% endif %}
            <ul class="blog-post-tags">
            {% for k in keywords %}
                <li class="uppercase">
                    <a href="{{ path('articles', {"fltreview[keyword_id]": k.id}) }}">{{ k.title }}</a>
                </li>
            {% endfor %}
            </ul>
        {% if style=='side' %}
        </div>
        {% endif %}
    {% endif %}

{% endmacro %}

{% macro renderArticleAuthors(authors) %}
    {% for a in authors %}
        <a href="{{ path('articles', {"fltreview[author_id]": a.author.id}) }}">{{ a.author.family }} {{ a.author.given }} <span class="badge badge-default">{{ a.author.articleCount }}</span></a>{% if not loop.last %}, {% endif %}
    {%  endfor %}
{% endmacro %}

{% macro renderAnnotatedTags(questions, style) %}
    {% set tags = [] %}
    {% for q in questions %}
        {% if not q.getNotApply %}
            {% set tags = tags|merge(getIfMultipleQuestionAnswers(q)) %}
        {% endif %}
    {% endfor %}
    {% if tags is not empty %}
        {% if style=='side' %}
        <div class="blog-single-sidebar-tags">
        <h3 class="blog-sidebar-title uppercase">annotation tags</h3>
        {% endif %}
            <ul class="blog-post-tags">
                {% for t in tags %}
                <li class="uppercase">
                    <a href="{{ path('articles', t.qid ) }}">{{ t.title }}</a>
                </li>
                {% endfor %}
            </ul>
        {% if style=='side' %}
        </div>
        {% endif %}
    {%  endif %}
{% endmacro %}

{% macro renderComment(comment) %}
    <div class="media">
        <div class="media-left">
            <a id="comment_{{ comment.id }}"><img alt="{{ comment.commenter.getUsername() }}" class="img-circle" src="{{ gravatar(comment.commenter.getEmail()) }}" /></a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">
                <a href="#">{{ comment.commenter.firstName }} {{ comment.commenter.lastName }}</a> on <span class="c-date">{{ comment.createdAt|date('d M Y H:i') }}</span>
            </h4>
            {{ comment.commentText }}
            {% if is_granted("edit", comment) %}
                <a href="{{ path('article_comment_update', {'articleId': comment.article.id, 'commentId': comment.id}) }}" class="btn">Edit</a>
            {% endif %}
            {% if is_granted("delete", comment) %}
                <a href="{{ path('article_comment_remove', {'articleId': comment.article.id, 'commentId': comment.id}) }}"
                   class="modal-confirm btn"
                   data-confirm-message="{{'app.article.comment_will_be_removed'|trans}}"
                   >{{ 'app.article.remove_comment'|trans }}</a>
            {% endif %}
        </div>
    </div>
{% endmacro %}

src/AppBundle/Resources/views/Article/blog_page.html.twig
{% extends 'SlxMetronicBundle::public.html.twig' %}
{% import 'SlxMetronicBundle::metronic_macros.html.twig' as metronic %}

{% block page_title %}{{ caption }}{% endblock %}
{% block portletTools %}{% endblock %}

{% block maincontent %}
    <div class="blog-page blog-content-2">
        <div class="row">
            <div class="col-lg-8">
                {% block blogcontent %}{% endblock %}
            </div>
            <div class="col-lg-4">
                <div class="blog-single-sidebar bordered blog-container">

                    {% if block('portletTools') is defined %}
                        {% set _block = block('portletTools') %}
                    {% else %}
                        {% set _block = "" %}
                    {% endif %}
                    {% if _block is not empty %}
                        <div class="blog-single-sidebar-recent">
                            <h4 class="blog-sidebar-title uppercase"><i class="fa fa-gears"></i> Editor actions</h4>
                            <ul>
                                {{ block('portletTools') }}
                            </ul>
                        </div>
                    {% endif %}

                    {% block sidebar %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock maincontent %}

src/AppBundle/Resources/views/Article/blog_post_page.html.twig
{% extends 'AppBundle:Article:blog_page.html.twig' %}
{% import 'SlxMetronicBundle::metronic_macros.html.twig' as metronic %}

{% block blogcontent %}
    <div class="blog-single-content bordered blog-container">
        <div class="blog-single-head">
            <h1 class="blog-single-head-title">{{ caption }}</h1>
        </div>
        {% block blogpost %}{% endblock %}
    </div>
{% endblock blogcontent %}

src/AppBundle/Resources/views/Article/blog_roll_page.html.twig
{% extends 'AppBundle:Article:blog_page.html.twig' %}
{% import 'SlxMetronicBundle::metronic_macros.html.twig' as metronic %}

{% block page_title %}{{ caption }}{% endblock %}
{% block portletTools %}{% endblock %}

{% block blogcontent %}

{% endblock blogcontent %}

src/AppBundle/Resources/views/Article/create_article.html.twig
{% extends 'SlxMetronicBundle::public_portletpage.html.twig' %}
{% import 'SlxMetronicBundle::metronic_macros.html.twig' as metronic %}

{% set formAction = path('article_create') %}
{% set pageCaption = 'slx_metronic.general.add'|trans %}

{% block page_title %}{{ "article"|trans }}{% endblock %}

{% set caption = pageCaption %}
{% set isForm = true %}
{% set portletIcon = 'pencil' %}

{% block formActions %}
    {{ form_widget(form.save) }}
{% endblock %}

{% block portlet_body -%}

    {{ form_start(form,{'action': formAction}) }}
    <input type="hidden" name="_method" value="POST" />
    <div class="form-body">
        {{ form_widget(form) }}
    </div>
{% endblock portlet_body %}

src/AppBundle/Resources/views/Article/create_review.html.twig
{% extends 'SlxMetronicBundle::public_portletpage.html.twig' %}
{% form_theme form 'AppBundle:Form:collection.html.twig' %}
{% import 'SlxMetronicBundle::metronic_macros.html.twig' as metronic %}
{% import '@App/Article/article_macros.html.twig' as amacros %}

{% set formAction = path('review_create', {'article_id': article.id}) %}
{% if isNewReview %}
    {% set pageCaption = 'slx_metronic.general.edit'|trans %}
{% else %}
    {% set pageCaption = 'slx_metronic.general.add'|trans %}
{% endif %}
{% block page_title %}{{ "article"|trans }}{% endblock %}

{% set caption = pageCaption %}
{% set isForm = true %}
{% set portletIcon = 'pencil' %}

{% block formActions %}
    {{ form_widget(form.save) }}
{% endblock %}

{% block portlet_body -%}
    <h2>{{ article.title }}</h2>
    <h3>{{ amacros.renderArticleAuthors(article.authors) }}</h3>
    <h4>
        {% if article.publishDate %}Year: {{ article.publishDate }} {% endif %}
        {% if article.doi %}DOI: {{ article.doi }} {% endif %}
        {% if article.url %}URL: {{ article.url }} {% endif %}
        {% if article.publisher %}Publisher: {{ article.publisher.title }} {% endif %}
        {% if article.journal %}Journal: {{ article.journal.title }} {% endif %}
    </h4>
    {{ form_start(form,{'action': formAction}) }}
    <input type="hidden" name="_method" value="POST"/>
    <div class="form-body">
        {{ form_widget(form) }}
    </div>
{% endblock portlet_body %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function () {
            function switchInputField(chk) {
                var inp = chk.closest('td').next('td').find('.answer_input');
                var isSelect2 = false;
                if (inp.length != 0) {
                    if ($(inp).data('select2')) {
                        isSelect2 = true;
                    }
                    if (chk.is(':checked')) {
                        if(isSelect2) {
                            inp.prop("disabled", true);
                        }
                        else {
                            inp.removeAttr('required');
                            inp.addClass('disabled');
                        }
                    }
                    else {
                        if(isSelect2) {
                            inp.prop("disabled", false);
                        }
                        else {
                            inp.prop('required', true);
                            inp.removeClass('disabled');
                        }
                    }
                }
            }

            $(".cm-not-apply-switch").on('click', function (ev) {
                var chk = $(ev.target);
                switchInputField(chk);
            });

            $('.js-select-multi-tags').each(function (index, element) {
                var sel = $(element);
                var questionId = sel.data("question");
                sel.select2({
                    tags: true,
                    tokenSeparators: [',', ' '],
                    createTag: function (params) {
                        var term = $.trim(params.term);

                        if (term === '') {
                            return null;
                        }
                        console.log("send question new answer to server");
                        return {
                            id: "#CREATE#"+term,
                            text: term,
                            isNew: true // add additional parameters
                        }
                    }
                });
            });

            // set disabled field on load
            $(".cm-not-apply-switch").each(function(idx){
                console.log(this);
                switchInputField($(this));
            });

        });
    </script>
{% endblock javascripts %}

src/AppBundle/Resources/views/Article/index.html.twig
{% extends 'AppBundle:Article:blog_roll_page.html.twig' %}
{% import 'SlxMetronicBundle::metronic_macros.html.twig' as metronic %}

{% block page_title %}{{ "app.article.articles"|trans }}{% endblock %}

{% block filter_form %}
    {% if filterForm is defined %}
        <h3 class="blog-sidebar-title uppercase">Annotated filters</h3>
        {% form_theme filterForm _self %}
        <form action="{{ path('articles') }}" class="form-horizontal" method="GET">
            <div class="form-body">
                {% for child in filterForm.children %}
                    {{ form_label(child) }}
                    {{ form_widget(child) }}
                {% endfor %}
            </div>
            <div class="form-actions">
                {{ metronic.button('slx_metronic.general.apply', 'submit', 'blue', 'ok') }}
            </div>
        </form>
    {% endif %}
{% endblock %}

{% block form_label %}
    <label>{{ translation_domain is same as(false) ? label : label|trans({}, translation_domain) }}</label>
{% endblock form_label %}

{% block portletTools %}
    <li><a href="{{ path('article_create') }}" >{{ 'app.article.add_article'|trans }}</a></li>
{% endblock portletTools %}

{% block blogcontent -%}

    {% if pagination is not empty %}
        {% for article in pagination %}
            {%  include('AppBundle:Default:_article_list_item.html.twig') %}
        {%  endfor %}
        {% if pagination is not null %}
            {{ knp_pagination_render(pagination, 'SlxMetronicBundle:Components:metronic_pagination_short.html.twig') }}
        {% endif %}

    {% else %}
        <p>{{ "app.article.no_articles"|trans }}</p>
    {% endif %}

{% endblock blogcontent %}

{% block sidebar %}
    {{ parent() }}
    <div class="blog-single-sidebar-ui">
        <p>{{ "app.article.articles"|trans }}: {{ pagination.getTotalItemCount }}</p>
    </div>
    {{ block("filter_form") }}
{% endblock %}

src/AppBundle/Resources/views/Article/show.html.twig
{% extends 'AppBundle:Article:blog_post_page.html.twig' %}
{% import 'SlxMetronicBundle::metronic_macros.html.twig' as metronic %}
{% import '@App/Article/article_macros.html.twig' as amacros %}

{% block page_title %}{{ article.title }}{% endblock %}

{% block portletTools %}
{% if is_granted("edit", article) %}
    <li><a href="{{ path('review_update', { 'article_id': article.id }) }}" >{{ 'app.general.edit'|trans }}</a></li>
    {% if article.status=="P" %}
    <li><a href="{{ path('article_unpublish', { 'article_id': article.id }) }}"
           class="modal-confirm"
           data-confirm-message="{{'app.article.article_will_be_unpublished'|trans}}"
        >{{ 'app.article.to_draft'|trans }}</a></li>
    {% elseif(article.canBePublished) %}
    <li><a href="{{ path('article_publish', { 'article_id': article.id }) }}" >{{ 'app.article.to_published'|trans }}</a></li>
    {% endif %}
    <li><a href="{{ path('article_delete', { 'article_id': article.id }) }}"
           class="modal-confirm"
           data-confirm-message="{{'slx_metronic.general.record_will_be_deleted'|trans}}"
        >{{ 'slx_metronic.general.delete'|trans }}</a></li>
{% endif %}
{% endblock portletTools %}

{% set caption %}
    {{ article.title }}
    {% if article.status is constant('STATUS_DRAFT', article) %}<span class="badge badge-warning">Draft</span>{% endif %}
{% endset %}
{% block blogpost %}
    <div class="blog-single-desc">
        {% include("AppBundle:Article:_article_info.html.twig") %}
        {% include("AppBundle:Article:_article_review.html.twig") %}
    </div>
    <div class="blog-single-foot">
        <div class="editor-info">
            <dl>
                <dt>{{ 'app.article.edited_by'|trans }}:</dt><dd>{{ article.owner.firstName }} {{ article.owner.lastName }},</dd>
                <dt>{{ 'app.general.created_at'|trans }}:</dt><dd>{{ article.createdAt|date('d M Y H:i') }}</dd>
                {% if article.updatedAt %}<dt>{{ 'app.general.updated_at'|trans }}:</dt><dd>{{ article.updatedAt|date('d M Y H:i') }}</dd>{% endif %}
            </dl>
        </div>
    </div>

    {% include("AppBundle:Article:_article_comments.html.twig") %}
{% endblock blogpost %}

{% block sidebar %}
    {{ parent() }}
    {% if article.review %}
        {{ amacros.renderAnnotatedTags(article.review.questions, "side") }}
    {% endif %}
    {{ amacros.renderArticleTags(article.getKeywords, "side") }}

{% endblock %}